<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pong Game</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
      background-color: #1a1a1a;
      transition: background-color 0.5s ease;
      opacity: 0;
      animation: fadeIn 0.5s ease forwards;
      display: flex;
      flex-direction: column; /* Imposta la direzione dei flex items in verticale */
      align-items: center; /* Centra gli elementi verticalmente */
      justify-content: center; /* Centra gli elementi orizzontalmente */
      height: 100vh; /* Imposta l'altezza del corpo a tutta l'altezza della finestra */
    }

    @keyframes fadeIn {
      to {
        opacity: 1;
      }
    }

    h1 {
      color: #ffffff;
      text-align: center;
      padding-top: 50px;
      font-size: 48px;
      text-transform: uppercase;
    }

    .animated-title {
      animation: neon 1.5s ease-in-out infinite alternate;
    }

    @keyframes neon {
      from {
        text-shadow: 0 0 10px #00ffff, 0 0 20px #00ffff, 0 0 30px #00ffff, 0 0 40px #00ffff, 0 0 70px #00ffff, 0 0 80px #00ffff, 0 0 100px #00ffff, 0 0 150px #00ffff;
      }
      to {
        text-shadow: 0 0 5px #00ffff, 0 0 10px #00ffff, 0 0 15px #00ffff, 0 0 20px #00ffff, 0 0 35px #00ffff, 0 0 40px #00ffff, 0 0 50px #00ffff, 0 0 75px #00ffff;
      }
    }

    .buttons-container {
      margin-top: 20px; /* Spazio sopra i pulsanti */
    }

    .game-button {
      padding: 15px 30px;
      background-color: #333;
      color: #fff;
      text-decoration: none;
      font-size: 24px;
      margin: 10px; /* Spazio tra i pulsanti */
      border: none;
      border-radius: 8px;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .game-button:hover {
      background-color: #555;
    }
  </style>
</head>
<body>
  <h1 class="animated-title">Welcome to Pong Game</h1>
  <div class="buttons-container">
    <button onclick="window.location.href='g1.html'" class="game-button">G1 (Single Player)</button>
    <button onclick="window.location.href='g2.html'" class="game-button">G2 (Two Players)</button>
  </div>

  <script>
    const canvas = document.getElementById('pongCanvas');
const context = canvas.getContext('2d');

let ball = {
  x: canvas.width / 2,
  y: canvas.height / 2,
  radius: 10,
  speedX: 3,
  speedY: 3
};

const originalBall = { ...ball };

const paddleHeight = 100;
const paddleWidth = 10;
const paddleSpeed = 5;

let paddleLeftY = (canvas.height - paddleHeight) / 2;
let paddleRightY = (canvas.height - paddleHeight) / 2;

let upPressed = false;
let downPressed = false;

let singlePlayer = true;
let score = 0;
let highScore = 0;
let player1Score = 0;
let botScore = 0;
let player1Wins = 0;
let botWins = 0;
let gameEnded = false;

const speedIncreasePercentage = 5;
const speedIncreaseFactor = 1 + speedIncreasePercentage / 100;

function drawBall() {
  context.beginPath();
  context.arc(ball.x, ball.y, ball.radius, 0, Math.PI * 2);
  context.fillStyle = 'white';
  context.fill();
  context.closePath();
}

function drawPaddles() {
  context.fillStyle = 'white';
  context.fillRect(0, paddleLeftY, paddleWidth, paddleHeight);
  context.fillRect(canvas.width - paddleWidth, paddleRightY, paddleWidth, paddleHeight);
}

function drawScores() {
  context.fillStyle = 'white';
  context.font = '16px Arial';
  context.fillText('Player: ' + player1Score + ' (Wins: ' + player1Wins + ')', 20, 20);
  context.fillText('Bot: ' + botScore + ' (Wins: ' + botWins + ')', canvas.width - 150, 20);
}

function draw() {
  context.clearRect(0, 0, canvas.width, canvas.height);
  drawBall();
  drawPaddles();
  drawScores();

  if (gameEnded) {
    context.fillStyle = 'white';
    context.font = '30px Arial';
    context.fillText('Game Over!', canvas.width / 2 - 100, canvas.height / 2);
    context.fillText('Press SPACE to restart', canvas.width / 2 - 150, canvas.height / 2 + 40);
    return;
  }

  if (upPressed && paddleLeftY > 0) {
    paddleLeftY -= paddleSpeed;
  } else if (downPressed && paddleLeftY < canvas.height - paddleHeight) {
    paddleLeftY += paddleSpeed;
  }

  // Move right paddle (bot)
  const paddleRightCenter = paddleRightY + paddleHeight / 2;
  if (paddleRightCenter < ball.y - 35) {
    paddleRightY += 5;
  } else if (paddleRightCenter > ball.y + 35) {
    paddleRightY -= 5;
  }

  ball.x += ball.speedX;
  ball.y += ball.speedY;

  if (ball.y + ball.radius > canvas.height || ball.y - ball.radius < 0) {
    ball.speedY = -ball.speedY * (Math.random() * 0.4 + 0.8);
  }

  if (ball.x - ball.radius < paddleWidth && ball.y > paddleLeftY && ball.y < paddleLeftY + paddleHeight) {
    ball.speedX = -ball.speedX;
    score++;
  } else if (ball.x + ball.radius > canvas.width - paddleWidth && ball.y > paddleRightY && ball.y < paddleRightY + paddleHeight) {
    ball.speedX = -ball.speedX;
    score++;
  } else if (ball.x - ball.radius < 0) {
    botScore++;
    checkWinner();
  } else if (ball.x + ball.radius > canvas.width) {
    player1Score++;
    checkWinner();
  }

  if (score > highScore) {
    highScore = score;
  }

  requestAnimationFrame(draw);
}

function checkWinner() {
  if (player1Score >= 5) {
    player1Wins++;
    endGame();
  } else if (botScore >= 5) {
    botWins++;
    endGame();
  }
}

function endGame() {
  gameEnded = true;
}

function resetGame() {
  ball = { ...originalBall };
  ball.x = canvas.width / 2;
  ball.y = canvas.height / 2;
  paddleLeftY = (canvas.height - paddleHeight) / 2;
  paddleRightY = (canvas.height - paddleHeight) / 2;
  score = 0;
  player1Score = 0;
  botScore = 0;
  gameEnded = false;
}

function keyDownHandler(e) {
  if (e.key === 'w') {
    upPressed = true;
  } else if (e.key === 's') {
    downPressed = true;
  } else if (e.key === ' ' && gameEnded) {
    resetGame();
    draw();
  }
}

function keyUpHandler(e) {
  if (e.key === 'w') {
    upPressed = false;
  } else if (e.key === 's') {
    downPressed = false;
  }
}

function startGame() {
  document.addEventListener('keydown', keyDownHandler, false);
  document.addEventListener('keyup', keyUpHandler, false);
  draw();
}

startGame();

setInterval(function() {
  ball.speedX *= speedIncreaseFactor;
  ball.speedY *= speedIncreaseFactor;
}, 1000);
const canvas = document.getElementById('pongCanvas');
const context = canvas.getContext('2d');

let ball = {
  x: canvas.width / 2,
  y: canvas.height / 2,
  radius: 10,
  speedX: 3,
  speedY: 3
};

const originalBall = { ...ball };

const paddleHeight = 100;
const paddleWidth = 10;
const paddleSpeed = 5;

let paddleLeftY = (canvas.height - paddleHeight) / 2;
let paddleRightY = (canvas.height - paddleHeight) / 2;

let upPressed = false;
let downPressed = false;

let wPressed = false;
let sPressed = false;

let singlePlayer = false;
let score = 0;
let highScore = 0;
let player1Score = 0;
let player2Score = 0;
let player1Wins = 0;
let player2Wins = 0;
let gameEnded = false;

const speedIncreasePercentage = 5;
const speedIncreaseFactor = 1 + speedIncreasePercentage / 100;

function drawBall() {
  context.beginPath();
  context.arc(ball.x, ball.y, ball.radius, 0, Math.PI * 2);
  context.fillStyle = 'white';
  context.fill();
  context.closePath();
}

function drawPaddles() {
  context.fillStyle = 'white';
  context.fillRect(0, paddleLeftY, paddleWidth, paddleHeight);
  context.fillRect(canvas.width - paddleWidth, paddleRightY, paddleWidth, paddleHeight);
}

function drawScores() {
  context.fillStyle = 'white';
  context.font = '16px Arial';
  context.fillText('Player 1: ' + player1Score + ' (Wins: ' + player1Wins + ')', 20, 20);
  context.fillText('Player 2: ' + player2Score + ' (Wins: ' + player2Wins + ')', canvas.width - 200, 20);
}

function draw() {
  context.clearRect(0, 0, canvas.width, canvas.height);
  drawBall();
  drawPaddles();
  drawScores();

  if (gameEnded) {
    context.fillStyle = 'white';
    context.font = '30px Arial';
    context.fillText('Game Over!', canvas.width / 2 - 100, canvas.height / 2);
    context.fillText('Press SPACE to restart', canvas.width / 2 - 150, canvas.height / 2 + 40);
    return;
  }

  if (wPressed && paddleLeftY > 0) {
    paddleLeftY -= paddleSpeed;
  } else if (sPressed && paddleLeftY < canvas.height - paddleHeight) {
    paddleLeftY += paddleSpeed;
  }

  if (upPressed && paddleRightY > 0) {
    paddleRightY -= paddleSpeed;
  } else if (downPressed && paddleRightY < canvas.height - paddleHeight) {
    paddleRightY += paddleSpeed;
  }

  ball.x += ball.speedX;
  ball.y += ball.speedY;

  if (ball.y + ball.radius > canvas.height || ball.y - ball.radius < 0) {
    ball.speedY = -ball.speedY * (Math.random() * 0.4 + 0.8);
  }

  if (ball.x - ball.radius < paddleWidth && ball.y > paddleLeftY && ball.y < paddleLeftY + paddleHeight) {
    ball.speedX = -ball.speedX;
    score++;
  } else if (ball.x + ball.radius > canvas.width - paddleWidth && ball.y > paddleRightY && ball.y < paddleRightY + paddleHeight) {
    ball.speedX = -ball.speedX;
    score++;
  } else if (ball.x - ball.radius < 0) {
    player2Score++;
    checkWinner();
  } else if (ball.x + ball.radius > canvas.width) {
    player1Score++;
    checkWinner();
  }

  if (score > highScore) {
    highScore = score;
  }

  requestAnimationFrame(draw);
}

function checkWinner() {
  if (player1Score >= 5) {
    player1Wins++;
    endGame();
  } else if (player2Score >= 5) {
    player2Wins++;
    endGame();
  }
}

function endGame() {
  gameEnded = true;
}

function resetGame() {
  ball = { ...originalBall };
  ball.x = canvas.width / 2;
  ball.y = canvas.height / 2;
  paddleLeftY = (canvas.height - paddleHeight) / 2;
  paddleRightY = (canvas.height - paddleHeight) / 2;
  score = 0;
  gameEnded = false;
}

function keyDownHandler(e) {
  if (e.key === 'w' || e.key === 'W') {
    wPressed = true;
  } else if (e.key === 's' || e.key === 'S') {
    sPressed = true;
  } else if (e.key === 'Up' || e.key === 'ArrowUp') {
    upPressed = true;
  } else if (e.key === 'Down' || e.key === 'ArrowDown') {
    downPressed = true;
  } else if (e.key === ' ' && gameEnded) {
    resetGame();
    draw();
  }
}

function keyUpHandler(e) {
  if (e.key === 'w' || e.key === 'W') {
    wPressed = false;
  } else if (e.key === 's' || e.key === 'S') {
    sPressed = false;
  } else if (e.key === 'Up' || e.key === 'ArrowUp') {
    upPressed = false;
  } else if (e.key === 'Down' || e.key === 'ArrowDown') {
    downPressed = false;
  }
}

function startGame() {
  document.addEventListener('keydown', keyDownHandler, false);
  document.addEventListener('keyup', keyUpHandler, false);
  draw();
}

startGame();

setInterval(function() {
  ball.speedX *= speedIncreaseFactor;
  ball.speedY *= speedIncreaseFactor;
}, 1000);

  </script>
</body>
</html>
